### ISSUE TITLE
Numerical Representation Issue

### ISSUE THREAD

**Issue by nicolacavallini** [ion-g-ion/torchTT#20] opened 2024-02-05 11:35 UTC
Dears,

I am having something that looks to me as numerical representation problems.

Here's and hopefully [self explanatory example](https://github.com/nicolacavallini/tt-ttorch-issue/blob/main/numerical_representation_issue.ipynb).

In essence I am trying to evaluate the same function in three different ways, and il looks like torchTT is provides a divergent value. 

Please let me know if I am getting something wrong. 

best,
NC

**Comment by ion-g-ion** [comment] 2024-02-06 11:50
Hi, 
thank you for reaching out. I cannot open the link because it seems to point on a local file 

BR,
Ion

**Comment by nicolacavallini** [comment] 2024-02-07 11:46
Gosh, my bad, I updated the link it should work now. 

best,
N

**Comment by ion-g-ion** [comment] 2024-02-07 16:17
Hi, I had a look at the script and the issue is that calling tn.Tensor with a fp64 numpy array as an argument returns a tensor that is fp32 (run `tn.Tensor(f1d.reshape(1,-1,1)).dtype`). How I would do is using the factory method `tn.tensor`. This returns the same precision as the input numpy array and moreover it can also change the representation using the dtype argument. I would change the cell to 
```
f_tt = tntt.TT([tn.tensor(f1d.reshape(1,-1,1), dtype=tn.float64),tn.tensor(f1d.reshape(1,-1,1), dtype=tn.float64)])
f_tt = f_tt.numpy()
```
Now the machine precision can be observed insted of 1e-8 which corresponds to truncating to fp32.
I had this kind of issue when I started to work with torch and it was leading to funny results and convergence plots.
I'll add a small remark in the documentation and in the examples and close the issue.

PS: `tntt.rank1TT()` can be used to represent rank1 tensors or the `**` operator for the kron product between `tntt.TT` objects.

**Closed** 2024-02-07 16:17 UTC
